# -*- coding: utf-8 -*-
"""Quiz Application_Techmaa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vq0jBBcdw_l04-4fV5fY0UHMxjWhBPvr
"""

print("**********")
print("Welome to Techmaa Quiz Application!!!")

# MCQ's prepaired

questions = [
    {
        "question": "1. Which SQL statement is used to extract data from a database?",
        "options": ["A. GET", "B. SELECT", "C. OPEN", "D. EXTRACT"],
        "answer": "B"
    },
    {
        "question": "2. In Python, what is the output of len([10, 20, 30])?",
        "options": ["A. 2", "B. 3", "C. 30", "D. Error"],
        "answer": "B"
    },
    {
        "question": "3. Which keyword is used to sort the result set in SQL?",
        "options": ["A. SORT", "B. ORDER", "C. ORDER BY", "D. SORT BY"],
        "answer": "C"
    },
    {
        "question": "4. In Python, what does the 'append()' method do in a list?",
        "options": [
            "A. Adds a new item at the end",
            "B. Removes an item",
            "C. Sorts the list",
            "D. Clears the list"
        ],
        "answer": "A"
    },
    {
        "question": "5. Which SQL clause is used to filter records?",
        "options": ["A. SELECT", "B. WHERE", "C. GROUP BY", "D. ORDER BY"],
        "answer": "B"
    },
    {
        "question": "6. What is the correct file extension for Python files?",
        "options": ["A. .pyth", "B. .pt", "C. .py", "D. .p"],
        "answer": "C"
    },
    {
        "question": "7. Which SQL function is used to count the number of rows in a table?",
        "options": ["A. SUM()", "B. COUNT()", "C. TOTAL()", "D. ROWS()"],
        "answer": "B"
    },
    {
        "question": "8. What will be the output of: print(type({})) in Python?",
        "options": ["A. <class 'list'>", "B. <class 'dict'>", "C. <class 'set'>", "D. <class 'tuple'>"],
        "answer": "B"
    },
    {
        "question": "9. In SQL, which command is used to remove all records from a table but keep the structure?",
        "options": ["A. DELETE", "B. REMOVE", "C. TRUNCATE", "D. DROP"],
        "answer": "C"
    },
    {
        "question": "10. In Python, which keyword is used to handle exceptions?",
        "options": ["A. except", "B. catch", "C. error", "D. exception"],
        "answer": "A"
    }
]



# MCQ's Result

def check_answer(user_guess, correct_answer):
    if user_guess == correct_answer:
        print("✅ Correct!")
        return True
    else:
        print("❌ Wrong Answer.")
        print(f"The correct answer is: {correct_answer}")
        return False

score = 0

for q in questions:
    print("****************")
    print(q["question"])
    for opt in q["options"]:
        print(opt)

    guess = input("Enter your answer (A/B/C/D): ").upper()
    if check_answer(guess, q["answer"]):
        score += 1

print(f"\n🎯 Your final score: {score}/{len(questions)}")


percentage = (score / len(questions)) * 100
if percentage >= 80:
    remark = "Excellent"
elif percentage >= 60:
    remark = "Good"
else:
    remark = "Needs Improvement"

print(f"\n🎯 Your final score: {score}/{len(questions)} ({percentage:.2f}%)")
print(f"💬 Remark: {remark}")

# Remark (Excellent/Good/Needs Improvement)

percentage = (score / len(questions)) * 100

if percentage >= 80:
    remark = "Excellent"
elif percentage >= 60:
    remark = "Good"
else:
    remark = "Needs Improvement"

print(f"\n🎯 Your final score: {score}/{len(questions)} ({percentage:.2f}%)")
print(f"💬 Remark: {remark}")

!pip install reportlab

# import libraries

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from datetime import datetime
import random

from reportlab.lib.pagesizes import landscape, A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

# Techmaa Logo need to add
from google.colab import files
uploaded = files.upload()

# Certificate Generator

def generate_certificate(name, score_percent, remark):
    file_name = f"certificate_{name}.pdf"
    c = canvas.Canvas(file_name, pagesize=landscape(A4))
    width, height = landscape(A4)

    # 🖼️ Border
    c.setStrokeColor(colors.black)
    c.setLineWidth(4)
    c.rect(0.5*inch, 0.5*inch, width - inch, height - inch)

    # 🖼️ Logo
    try:
        c.drawImage("certified_PNG24.png", width/2 - 1*inch, height - 2*inch, width=2*inch, height=1.5*inch, preserveAspectRatio=True)
    except:
        print("⚠️ Logo not found — upload 'certified_PNG24.png' before generating the certificate.")

    # 🏆 Title
    c.setFont("Helvetica-Bold", 28)
    c.drawCentredString(width/2, height - 2.8*inch, "Certificate of Achievement")

    # ✨ Subtitle
    c.setFont("Helvetica", 16)
    c.drawCentredString(width/2, height - 3.6*inch, "This is to certify that")

    # 👤 Name
    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(width/2, height - 4.5*inch, name)

    # 🧠 Quiz result
    c.setFont("Helvetica", 16)
    c.drawCentredString(width/2, height - 5.5*inch,
                        f"has successfully completed the quiz with a score of {score_percent:.2f}%")

    # 💬 Remark
    c.setFont("Helvetica-Oblique", 16)
    c.drawCentredString(width/2, height - 6.3*inch, f"Remark: {remark}")

    # ✍️ Signature and Date lines
    c.line(width/2 - 3*inch, height - 7*inch, width/2 - 1*inch, height - 7*inch)
    c.line(width/2 + 1*inch, height - 7*inch, width/2 + 3*inch, height - 7*inch)

    c.setFont("Helvetica", 12)
    c.drawString(width/2 - 2.8*inch, height - 7.3*inch, "Authorized Signature")
    c.drawString(width/2 + 1.2*inch, height - 7.3*inch, "Date")

    # 🕓 Date
    c.setFont("Helvetica", 12)
    c.drawString(width/2 + 1.2*inch, height - 7.5*inch, datetime.now().strftime("%Y-%m-%d"))

    # 🔢 Certificate ID
    cert_id = f"CERT-{random.randint(10000,99999)}"
    c.setFont("Helvetica-Oblique", 10)
    c.drawRightString(width - inch, 0.7*inch, f"Certificate ID: {cert_id}")

    c.save()
    print(f"🏅 Certificate saved as: {file_name}")

generate_certificate("Ashwini", 95, "Excellent")